### ISSUE TITLE
No se puede subir mas de un archivo

### ISSUE THREAD

**Issue by inakijaneiro** [manueleduar/AGACE#12]
Como hay un redirect al final del route del archivo, al querer subir dos o más archivos se manda a llamar el redirect varias veces, lo que genera un error:
`[ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client busboy`

Revisar: `server/api/denuncias/denuncias.js` línea 75 (ahí es cuando sucede el redirect múltiple)

**Comment by HectorNLeon** [comment]
Se arreglo en la branch denuncias
